// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srrulricjrvduqjncinp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycnVscmljanJ2ZHVxam5jaW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwNzg2NzEsImV4cCI6MjA0OTY1NDY3MX0.CMj3Z3G0ufjqsfbUTUTCb7yKfVir0qf9umkhBejs_5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);